apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-color
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: webapp-color
    repoURL: https://marcusjava.github.io/helm-charts-repo/
    targetRevision: 0.1.1
    helm:
      values: |
        replicaCount: 2
        app:
          color: green  # red,green,blue,blue2,pink,darkblue
      # valueFiles:
      #   - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
